/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import main.Main;

public class App {
    public static void main(String[] args) {
        new Main.main(args);
    }
}
