/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.ui.UiStarter;

import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        Application.launch(UiStarter.class, args);

    }
}
